---
- hosts: wireguard
  any_errors_fatal: true
  gather_facts: yes
  tasks:
    - name: Update packages
      apt:
        update_cache: yes
        cache_valid_time: 3600
      become: yes

    - name: Install Wireguard
      apt:
        name: wireguard
        state: present
      become: yes

    - name: Generate Wireguard key pair
      shell: wg genkey | tee /etc/wireguard/privatekey | wg pubkey | tee /etc/wireguard/publickey
      args:
        creates: /etc/wireguard/privatekey
      become: yes

    - name: Register private key
      shell: cat /etc/wireguard/privatekey
      register: wireguard_private_key
      changed_when: false
      become: yes

    - name: Register public key
      shell: cat /etc/wireguard/publickey
      register: wireguard_public_key
      changed_when: false
      become: yes

    - name: Generate pre-shared keyskeypair
      shell: "wg genpsk > /etc/wireguard/psk-{{ item }}"
      args:
        creates: "/etc/wireguard/psk-{{ item }}"
      when: inventory_hostname < item
      with_items: "{{ groups['wireguard'] }}"
      become: yes

    - name: Register pre-shared key
      shell: "cat /etc/wireguard/psk-{{ item }}"
      register: wireguard_preshared_key
      changed_when: false
      when: inventory_hostname < item
      with_items: "{{ groups['wireguard'] }}"
      become: yes

    - name: Massage pre-shared keys
      set_fact: "wireguard_preshared_keys={{ wireguard_preshared_keys | default({}) | combine({item.item: item.stdout}) }}"
      when: item.skipped is not defined
      with_items: "{{ wireguard_preshared_key.results }}"
      become: yes

    - name: Setup wg0 device
      template:
        src: ./templates/systemd.netdev
        dest: /etc/systemd/network/99-wg0.netdev
        owner: root
        group: systemd-network
        mode: 0640
      become: yes
      notify: Restart Networkd

    - name: Setup wg0 network
      template:
        src: ./templates/systemd.network
        dest: /etc/systemd/network/99-wg0.network
        owner: root
        group: systemd-network
        mode: 0640
      become: yes
      notify: Restart Networkd

  handlers:
    - name: Restart Networkd
      service:
        name: systemd-networkd
        state: restarted
        enabled: yes
      become: yes
